/**
 * Purpose: fetch a complete runtime source snapshot for browser boot.
 * Assumes: tools/bundle-runtime.mjs emits runtime.json and wasm assets beside
 *   it [source: extensions/node/tools/bundle-runtime.mjs; commit=WORKTREE].
 * Guarantees: source paths are validated before any file is mounted
 *   [source: extensions/node/src/platform-browser.ts:prepareRuntime; commit=WORKTREE].
 * Owns resources: a prepared snapshot owns its source strings until boot
 *   returns; the engine owns the WebAssembly filesystem receiving the copy.
 */

import { EngineError, SourceNotFoundError, UnsupportedError } from "./errors.ts";
import type { PreparedRuntime, RuntimeFS } from "./platform.ts";

declare const __METTA_PACKAGE_VERSION__: string;
declare const __SWIPL_DATA_SIZE__: number;

/** The browser distribution's package URL. */
export const packageRoot: string = new URL("../", import.meta.url).href;
/** The source and wasm assets emitted by the browser build. */
export const repoRoot: string = new URL("../_runtime/", import.meta.url).href;

/** Host filesystem paths have no browser counterpart. */
export function resolvePath(_path: string): string {
  throw new UnsupportedError(
    "loadFile and libraryPath read host filesystem paths and are unavailable in a browser; " +
      "use run or load for source text",
  );
}

/** Browser code cannot inspect a host directory. */
export function isDirectory(_path: string): boolean {
  throw new UnsupportedError("a browser cannot inspect a host filesystem directory");
}

/** A browser caller supplies source text to lint rather than a host path. */
export function readTextFile(_path: string): string {
  throw new UnsupportedError(
    "lintFile reads a host filesystem path and is unavailable in a browser; use lint for source text",
  );
}

/** Browser runtime sources are installed by prepareRuntime. */
export function mountInto(
  _fs: RuntimeFS,
  _hostDir: string,
  _virtualDir: string,
  _keep?: (name: string) => boolean,
): void {
  throw new UnsupportedError(
    "mount reads a host filesystem directory and is unavailable in a browser",
  );
}

/** The package version embedded by the browser build. */
export function runtimeVersion(): string {
  return __METTA_PACKAGE_VERSION__;
}

/** Fetch and validate all sources before allocating the wasm engine. */
export async function prepareRuntime(root: string): Promise<PreparedRuntime> {
  let base: URL;
  try {
    base = new URL(root, repoRoot);
    if (!base.pathname.endsWith("/")) base.pathname += "/";
  } catch (error) {
    throw new SourceNotFoundError(`browser runtime root is not a URL: ${root}`, { cause: error });
  }
  const url = new URL("runtime.json", base);
  let raw: unknown;
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP ${String(response.status)} ${response.statusText}`);
    }
    raw = await response.json();
  } catch (error) {
    throw new SourceNotFoundError(
      `browser runtime manifest could not be read at ${url.href}; serve the _runtime ` +
        "directory generated by the browser build",
      { cause: error },
    );
  }
  if (typeof raw !== "object" || raw === null ||
      !("version" in raw) || raw.version !== 1 ||
      !("files" in raw) || !Array.isArray(raw.files)) {
    throw new EngineError(`browser runtime manifest at ${url.href} has an invalid format`);
  }
  const files: { path: string; text: string }[] = [];
  const seen = new Set<string>();
  for (const entry of raw.files as unknown[]) {
    if (typeof entry !== "object" || entry === null ||
        !("path" in entry) || typeof entry.path !== "string" ||
        !("text" in entry) || typeof entry.text !== "string") {
      throw new EngineError(`browser runtime manifest at ${url.href} has an invalid source entry`);
    }
    const path = entry.path;
    const parts = path.split("/");
    if (parts.some((part) => part === "" || part === "." || part === "..") ||
        /[\\\u0000-\u001f\u007f]/.test(path) || seen.has(path) ||
        !/^(?:bridge\.pl|(?:engine|lib)\/.+\.(?:pl|metta)|extensions\/[^/]+\/extension\.pl)$/.test(path)) {
      throw new EngineError(`browser runtime manifest has an invalid or duplicate source path: ${path}`);
    }
    seen.add(path);
    files.push({ path, text: entry.text });
  }
  for (const { path } of files) {
    const parts = path.split("/");
    for (let index = 1; index < parts.length; index++) {
      const parent = parts.slice(0, index).join("/");
      if (seen.has(parent)) {
        throw new EngineError(`browser runtime manifest source is also used as a directory: ${parent}`);
      }
    }
  }
  for (const required of ["engine/metta.pl", "engine/prelude.metta", "lib/lib_builtin_types/lib_builtin_types.metta", "bridge.pl"]) {
    if (!seen.has(required)) {
      throw new EngineError(`browser runtime manifest is missing ${required}`);
    }
  }
  // Fetch first: the generated loader's async preRun data download otherwise
  // leaves its factory pending when the request fails. Emscripten exposes both
  // injection hooks through swipl-wasm's factory configuration.
  // https://cdn.jsdelivr.net/npm/swipl-wasm@8.0.6/dist/swipl/swipl-web.js
  const assets = await Promise.all(["swipl-web.wasm", "swipl-web.data"].map(async (name) => {
    const asset = new URL(`wasm/${name}`, base);
    try {
      const response = await fetch(asset);
      if (!response.ok) throw new Error(`HTTP ${String(response.status)} ${response.statusText}`);
      return await response.arrayBuffer();
    } catch (error) {
      throw new SourceNotFoundError(`browser runtime asset could not be read at ${asset.href}`, { cause: error });
    }
  }));
  const wasm = assets[0] as ArrayBuffer;
  const data = assets[1] as ArrayBuffer;
  // Validate before invoking the loader: even its preload hook runs inside an
  // unawaited async function. The build records the colocated data file size.
  if (data.byteLength !== __SWIPL_DATA_SIZE__) {
    throw new EngineError(
      `browser runtime asset swipl-web.data has ${String(data.byteLength)} bytes; ` +
        `the wasm loader expects ${String(__SWIPL_DATA_SIZE__)}`,
    );
  }
  return {
    mount(fs): void {
      for (const file of files) {
        const path = `/metta/${file.path}`;
        fs.mkdirTree(path.slice(0, path.lastIndexOf("/")));
        fs.writeFile(path, file.text);
      }
    },
    options: {
      locateFile: (name: string): string => new URL(`wasm/${name}`, base).href,
      wasmBinary: new Uint8Array(wasm),
      getPreloadedPackage: (): ArrayBuffer => data,
    },
  };
}
