/**
 * Purpose: what each refusal field holds as it crosses, by the engine's own
 *   field name, so the refusal decoder in engine.ts reads a number field as a
 *   number and a term field as this package's own atom, and errors.ts derives
 *   each refusal's field types from it.
 * Guarantees:
 *   - this file is GENERATED by extensions/python/tools/refusalgen.py from the
 *     engine's metta_host_error_field_row/2, beside the Python seat's
 *     FIELD_PAYLOADS in metta/_errors/refusals.py; edit the table in
 *     engine/metta/registration.pl and rerun it with --write, never this
 *     file, and the `refusal-sync` lane fails on any drift [tested 2026-09-29T07:01:58+10:00:
 *     "types every field as the shared kind list does"]
 *   - every payload is a word of the `wire-payload` vocabulary, which
 *     errors.ts's field types require of it at compile time
 * Open Obligations: None.
 */

/**
 * What each refusal field holds, by the engine's field name: `text` a name
 * or a sentence, `number` a count or a bound, `term` a MeTTa atom that
 * crosses encoded and decodes into this package's own atom.
 */
export const RefusalFieldPayload = {
  bound: "number",
  call: "text",
  capability: "text",
  costs: "text",
  culprit: "text",
  expected: "text",
  head: "text",
  key: "term",
  kind: "text",
  limit: "number",
  line: "number",
  operation: "text",
  requires: "text",
  restraint: "text",
  source: "text",
  space: "text",
} as const;
