/**
 * Purpose: the engine's own closed value sets, as TypeScript unions, so a
 *   program that names one of these names it exactly and a typo is a compile
 *   error rather than an answer that never comes.
 * Assumes:
 *   - each block below is one `(vocabulary ...)` row in the `&metta` catalog,
 *     whose presets live in `engine/spaces/catalog.pl`
 * Guarantees:
 *   - this file is GENERATED by extensions/python/tools/vocabgen.py from the
 *     engine's own `(vocabulary ...)` rows, beside the Python module the same
 *     tool writes; edit the presets in engine/spaces/catalog.pl and rerun it
 *     with --write, never this file, and the `vocab-sync` lane fails on any
 *     drift [tested: test_the_vocabulary_module_is_generated; commit=a376df6dff8099d6145ace55132c7e30922ea1de]
 *   - every table here matches its catalog row exactly, values in the
 *     catalog's own order, and the test that checks it BOOTS the engine and
 *     reads `&metta` rather than reading a copy of this file, so the two
 *     cannot drift [tested: "every vocabulary here matches the engine's own";
 *     commit=bbb512316280110a747e31c26adfc31e8c5104be]
 *   - `AlgebraLaw` publishes every accepted declaration spelling, read from
 *     the same live catalog row [tested: "every vocabulary here matches the
 *     engine's own"; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
 *   - a value's KEY is this package's own casing map applied to the word, so
 *     `AnswerPolicy.bestFirst` is `"best-first"`, exactly as `S.bestFirst` is
 *     the symbol `best-first`. A word the map leaves alone keeps its exact
 *     spelling, which is why `OpKind.raw_det` carries an underscore the style
 *     guide would otherwise refuse: it is the engine's word, not an identifier
 *     this package chose
 * Decides: a const object plus a derived union type, not an `enum`. The
 *   package compiles under `erasableSyntaxOnly`, which refuses `enum` because
 *   an enum emits runtime code that type stripping cannot erase; the const
 *   object is the shape TypeScript's own documentation recommends in its
 *   place, and it has the property an enum lacks — the VALUES are the engine's
 *   own words, so a bare string still passes every door.
 * Open Obligations:
 *   To Do: None
 *   Hacks: None
 *   Future Enhancements: None
 */

/** The `ClauseFailedEnum` vocabulary, in the catalog's own order. */
export const ClauseFailedEnum = {
  ClauseFailNonDet: "ClauseFailNonDet",
  ClauseFailDet: "ClauseFailDet",
} as const;

/** One value of the `ClauseFailedEnum` vocabulary. */
export type ClauseFailedEnum = (typeof ClauseFailedEnum)[keyof typeof ClauseFailedEnum];

/** The `EvaluationOrderEnum` vocabulary, in the catalog's own order. */
export const EvaluationOrderEnum = {
  OrderClause: "OrderClause",
  OrderFittest: "OrderFittest",
} as const;

/** One value of the `EvaluationOrderEnum` vocabulary. */
export type EvaluationOrderEnum = (typeof EvaluationOrderEnum)[keyof typeof EvaluationOrderEnum];

/** The `FunctionResultEnum` vocabulary, in the catalog's own order. */
export const FunctionResultEnum = {
  Nondeterministic: "Nondeterministic",
  Deterministic: "Deterministic",
} as const;

/** One value of the `FunctionResultEnum` vocabulary. */
export type FunctionResultEnum = (typeof FunctionResultEnum)[keyof typeof FunctionResultEnum];

/** The `MismatchEnum` vocabulary, in the catalog's own order. */
export const MismatchEnum = {
  MismatchOriginal: "MismatchOriginal",
  MismatchError: "MismatchError",
  MismatchFail: "MismatchFail",
} as const;

/** One value of the `MismatchEnum` vocabulary. */
export type MismatchEnum = (typeof MismatchEnum)[keyof typeof MismatchEnum];

/** The `NoMatchEnum` vocabulary, in the catalog's own order. */
export const NoMatchEnum = {
  NoMatchOriginal: "NoMatchOriginal",
  NoMatchFail: "NoMatchFail",
  NoMatchError: "NoMatchError",
} as const;

/** One value of the `NoMatchEnum` vocabulary. */
export type NoMatchEnum = (typeof NoMatchEnum)[keyof typeof NoMatchEnum];

/** The `OutOfClausesEnum` vocabulary, in the catalog's own order. */
export const OutOfClausesEnum = {
  FailureOriginal: "FailureOriginal",
  FailureEmpty: "FailureEmpty",
  FailureError: "FailureError",
} as const;

/** One value of the `OutOfClausesEnum` vocabulary. */
export type OutOfClausesEnum = (typeof OutOfClausesEnum)[keyof typeof OutOfClausesEnum];

/** The `agenda-policy` vocabulary, in the catalog's own order. */
export const AgendaPolicy = {
  declaration: "declaration",
  recency: "recency",
  specificity: "specificity",
  priority: "priority",
  user: "user",
} as const;

/** One value of the `agenda-policy` vocabulary. */
export type AgendaPolicy = (typeof AgendaPolicy)[keyof typeof AgendaPolicy];

/** The `algebra-law` vocabulary, in the catalog's own order. */
export const AlgebraLaw = {
  combineAssociative: "combine-associative",
  combineCommutative: "combine-commutative",
  extendAssociative: "extend-associative",
  extendCommutative: "extend-commutative",
  leftDistributive: "left-distributive",
  rightDistributive: "right-distributive",
  combineIdempotent: "combine-idempotent",
  combineZeroIdentity: "combine-zero-identity",
  extendOneIdentity: "extend-one-identity",
  extendZeroAnnihilates: "extend-zero-annihilates",
  contraction: "contraction",
  roundtrip: "roundtrip",
  equivalent: "equivalent",
  associative: "associative",
  commutative: "commutative",
  distributive: "distributive",
  idempotent: "idempotent",
  identity: "identity",
  distributesOver: "distributes-over",
} as const;

/** One value of the `algebra-law` vocabulary. */
export type AlgebraLaw = (typeof AlgebraLaw)[keyof typeof AlgebraLaw];

/** The `answer-policy` vocabulary, in the catalog's own order. */
export const AnswerPolicy = {
  depth: "depth",
  fair: "fair",
  bestFirst: "best-first",
} as const;

/** One value of the `answer-policy` vocabulary. */
export type AnswerPolicy = (typeof AnswerPolicy)[keyof typeof AnswerPolicy];

/** The `applicability` vocabulary, in the catalog's own order. */
export const Applicability = {
  machine: "machine",
  maybe: "maybe",
  prose: "prose",
} as const;

/** One value of the `applicability` vocabulary. */
export type Applicability = (typeof Applicability)[keyof typeof Applicability];

/** The `argument-delivery` vocabulary, in the catalog's own order. */
export const ArgumentDelivery = {
  atoms: "atoms",
  values: "values",
} as const;

/** One value of the `argument-delivery` vocabulary. */
export type ArgumentDelivery = (typeof ArgumentDelivery)[keyof typeof ArgumentDelivery];

/** The `atomicity` vocabulary, in the catalog's own order. */
export const Atomicity = {
  transactional: "transactional",
  atomicSingle: "atomic-single",
  bestEffort: "best-effort",
} as const;

/** One value of the `atomicity` vocabulary. */
export type Atomicity = (typeof Atomicity)[keyof typeof Atomicity];

/** The `cache-policy` vocabulary, in the catalog's own order. */
export const CachePolicy = {
  force: "force",
  refuse: "refuse",
  plain: "plain",
  incremental: "incremental",
  monotonic: "monotonic",
  lazy: "lazy",
  shared: "shared",
  private: "private",
  subsumptive: "subsumptive",
  lattice: "lattice",
  maxAnswers: "max-answers",
  subgoalAbstract: "subgoal-abstract",
  answerAbstract: "answer-abstract",
} as const;

/** One value of the `cache-policy` vocabulary. */
export type CachePolicy = (typeof CachePolicy)[keyof typeof CachePolicy];

/** The `cost-class` vocabulary, in the catalog's own order. */
export const CostClass = {
  constant: "constant",
  log: "log",
  linear: "linear",
  linearithmic: "linearithmic",
  quadratic: "quadratic",
  exponential: "exponential",
} as const;

/** One value of the `cost-class` vocabulary. */
export type CostClass = (typeof CostClass)[keyof typeof CostClass];

/** The `delivery` vocabulary, in the catalog's own order. */
export const Delivery = {
  atMostOnce: "at-most-once",
  atLeastOnce: "at-least-once",
  perWriteExactly: "per-write-exactly",
} as const;

/** One value of the `delivery` vocabulary. */
export type Delivery = (typeof Delivery)[keyof typeof Delivery];

/** The `delta-kind` vocabulary, in the catalog's own order. */
export const DeltaKind = {
  add: "add",
  remove: "remove",
  progress: "progress",
} as const;

/** One value of the `delta-kind` vocabulary. */
export type DeltaKind = (typeof DeltaKind)[keyof typeof DeltaKind];

/** The `determinism` vocabulary, in the catalog's own order. */
export const Determinism = {
  det: "det",
  semidet: "semidet",
  nondet: "nondet",
} as const;

/** One value of the `determinism` vocabulary. */
export type Determinism = (typeof Determinism)[keyof typeof Determinism];

/** The `effect-class` vocabulary, in the catalog's own order. */
export const EffectClass = {
  pureStructural: "pureStructural",
  readOnlyLookup: "readOnlyLookup",
  nondeterministicReadOnly: "nondeterministicReadOnly",
  writesState: "writesState",
  oracleIO: "oracleIO",
} as const;

/** One value of the `effect-class` vocabulary. */
export type EffectClass = (typeof EffectClass)[keyof typeof EffectClass];

/** The `event-order` vocabulary, in the catalog's own order. */
export const EventOrder = {
  ordered: "ordered",
  unordered: "unordered",
} as const;

/** One value of the `event-order` vocabulary. */
export type EventOrder = (typeof EventOrder)[keyof typeof EventOrder];

/** The `fidelity` vocabulary, in the catalog's own order. */
export const Fidelity = {
  Exact: "Exact",
  Partial: "Partial",
  Sound: "Sound",
  Refuse: "Refuse",
} as const;

/** One value of the `fidelity` vocabulary. */
export type Fidelity = (typeof Fidelity)[keyof typeof Fidelity];

/** The `ground-kind` vocabulary, in the catalog's own order. */
export const GroundKind = {
  hostReference: "host-reference",
  mettaLaw: "metta-law",
  arbiter: "arbiter",
} as const;

/** One value of the `ground-kind` vocabulary. */
export type GroundKind = (typeof GroundKind)[keyof typeof GroundKind];

/** The `image-mode` vocabulary, in the catalog's own order. */
export const ImageMode = {
  opaque: "opaque",
  transparent: "transparent",
  auto: "auto",
} as const;

/** One value of the `image-mode` vocabulary. */
export type ImageMode = (typeof ImageMode)[keyof typeof ImageMode];

/** The `journal-sync` vocabulary, in the catalog's own order. */
export const JournalSync = {
  none: "none",
  flush: "flush",
  close: "close",
} as const;

/** One value of the `journal-sync` vocabulary. */
export type JournalSync = (typeof JournalSync)[keyof typeof JournalSync];

/** The `limit` vocabulary, in the catalog's own order. */
export const Limit = {
  events: "events",
  memory: "memory",
  inferences: "inferences",
  timeout: "timeout",
  stack: "stack",
} as const;

/** One value of the `limit` vocabulary. */
export type Limit = (typeof Limit)[keyof typeof Limit];

/** The `live-strategy` vocabulary, in the catalog's own order. */
export const LiveStrategy = {
  pattern: "pattern",
  heads: "heads",
  tabled: "tabled",
} as const;

/** One value of the `live-strategy` vocabulary. */
export type LiveStrategy = (typeof LiveStrategy)[keyof typeof LiveStrategy];

/** The `memo-aggregate` vocabulary, in the catalog's own order. */
export const MemoAggregate = {
  none: "none",
  min: "min",
  max: "max",
  sum: "sum",
  count: "count",
} as const;

/** One value of the `memo-aggregate` vocabulary. */
export type MemoAggregate = (typeof MemoAggregate)[keyof typeof MemoAggregate];

/** The `memo-strategy` vocabulary, in the catalog's own order. */
export const MemoStrategy = {
  wtinylfu: "wtinylfu",
  lru: "lru",
} as const;

/** One value of the `memo-strategy` vocabulary. */
export type MemoStrategy = (typeof MemoStrategy)[keyof typeof MemoStrategy];

/** The `numeric-type` vocabulary, in the catalog's own order. */
export const NumericType = {
  Number: "Number",
  BigInt: "BigInt",
} as const;

/** One value of the `numeric-type` vocabulary. */
export type NumericType = (typeof NumericType)[keyof typeof NumericType];

/** The `on-error-mode` vocabulary, in the catalog's own order. */
export const OnError = {
  keep: "keep",
  empty: "empty",
  abort: "abort",
} as const;

/** One value of the `on-error-mode` vocabulary. */
export type OnError = (typeof OnError)[keyof typeof OnError];

/** The `op-kind` vocabulary, in the catalog's own order. */
export const OpKind = {
  det: "det",
  many: "many",
  async: "async",
  raw_det: "raw_det",
  raw_many: "raw_many",
} as const;

/** One value of the `op-kind` vocabulary. */
export type OpKind = (typeof OpKind)[keyof typeof OpKind];

/**
 * The `provider-capability` vocabulary, in the catalog's own order.
 *
 * The engine declares this vocabulary OPEN, so the type also admits a
 * word registered through `(add-atom &metta (vocabulary-member
 * provider-capability <word>))`; the words below are the ones it ships.
 */
export const ProviderCapability = {
  match: "match",
  enumerate: "enumerate",
  add: "add",
  addMany: "add-many",
  remove: "remove",
  clear: "clear",
  subscribe: "subscribe",
  plan: "plan",
  rules: "rules",
  tokens: "tokens",
  addToken: "add-token",
  removeToken: "remove-token",
} as const;

/** One value of the `provider-capability` vocabulary. */
export type ProviderCapability = (typeof ProviderCapability)[keyof typeof ProviderCapability] | (string & {});

/** The `refinement` vocabulary, in the catalog's own order. */
export const Refinement = {
  Gt: "Gt",
  Ge: "Ge",
  Lt: "Lt",
  Le: "Le",
  Interval: "Interval",
  MultipleOf: "MultipleOf",
  MinLen: "MinLen",
  MaxLen: "MaxLen",
  Len: "Len",
  Predicate: "Predicate",
  Unit: "Unit",
  Literal: "Literal",
} as const;

/** One value of the `refinement` vocabulary. */
export type Refinement = (typeof Refinement)[keyof typeof Refinement];

/** The `refusal-kind` vocabulary, in the catalog's own order. */
export const RefusalKind = {
  syntax: "syntax",
  time_limit: "time_limit",
  inference_limit: "inference_limit",
  restraint: "restraint",
  interrupted: "interrupted",
  value: "value",
  type: "type",
  assertion: "assertion",
  capability: "capability",
  operation: "operation",
  stack: "stack",
  source: "source",
  engine: "engine",
} as const;

/** One value of the `refusal-kind` vocabulary. */
export type RefusalKind = (typeof RefusalKind)[keyof typeof RefusalKind];

/** The `registry-image` vocabulary, in the catalog's own order. */
export const RegistryImage = {
  expression: "expression",
  symbol: "symbol",
  handle: "handle",
  operations: "operations",
} as const;

/** One value of the `registry-image` vocabulary. */
export type RegistryImage = (typeof RegistryImage)[keyof typeof RegistryImage];

/** The `remedy-kind` vocabulary, in the catalog's own order. */
export const RemedyKind = {
  quickfix: "quickfix",
  refactor: "refactor",
  source: "source",
} as const;

/** One value of the `remedy-kind` vocabulary. */
export type RemedyKind = (typeof RemedyKind)[keyof typeof RemedyKind];

/** The `route-key` vocabulary, in the catalog's own order. */
export const RouteKey = {
  context: "context",
  global: "global",
} as const;

/** One value of the `route-key` vocabulary. */
export type RouteKey = (typeof RouteKey)[keyof typeof RouteKey];

/** The `save-format` vocabulary, in the catalog's own order. */
export const SaveFormat = {
  metta: "metta",
  fast: "fast",
} as const;

/** One value of the `save-format` vocabulary. */
export type SaveFormat = (typeof SaveFormat)[keyof typeof SaveFormat];

/**
 * The `semiring` vocabulary, in the catalog's own order.
 *
 * The engine declares this vocabulary OPEN, so the type also admits a
 * word registered through `(add-atom &metta (vocabulary-member
 * semiring <word>))`; the words below are the ones it ships.
 */
export const Semiring = {
  bool: "bool",
  visibility: "visibility",
  bag: "bag",
  counting: "counting",
  set: "set",
  ranked: "ranked",
  tropical: "tropical",
  prob: "prob",
  prov: "prov",
  budget: "budget",
  amplitude: "amplitude",
} as const;

/** One value of the `semiring` vocabulary. */
export type Semiring = (typeof Semiring)[keyof typeof Semiring] | (string & {});

/** The `semiring-order` vocabulary, in the catalog's own order. */
export const SemiringOrder = {
  ascending: "ascending",
  descending: "descending",
} as const;

/** One value of the `semiring-order` vocabulary. */
export type SemiringOrder = (typeof SemiringOrder)[keyof typeof SemiringOrder];

/** The `source-kind` vocabulary, in the catalog's own order. */
export const SourceKind = {
  linear: "linear",
  repeated: "repeated",
  peek: "peek",
} as const;

/** One value of the `source-kind` vocabulary. */
export type SourceKind = (typeof SourceKind)[keyof typeof SourceKind];

/** The `space-capability` vocabulary, in the catalog's own order. */
export const SpaceCapability = {
  file: "file",
  process: "process",
  network: "network",
} as const;

/** One value of the `space-capability` vocabulary. */
export type SpaceCapability = (typeof SpaceCapability)[keyof typeof SpaceCapability];

/** The `subscription-edge` vocabulary, in the catalog's own order. */
export const SubscriptionEdge = {
  add: "add",
  remove: "remove",
  both: "both",
} as const;

/** One value of the `subscription-edge` vocabulary. */
export type SubscriptionEdge = (typeof SubscriptionEdge)[keyof typeof SubscriptionEdge];

/** The `visibility` vocabulary, in the catalog's own order. */
export const Visibility = {
  PUBLIC: "PUBLIC",
  INTERNAL: "INTERNAL",
} as const;

/** One value of the `visibility` vocabulary. */
export type Visibility = (typeof Visibility)[keyof typeof Visibility];

/** The `volatility` vocabulary, in the catalog's own order. */
export const Volatility = {
  volatile: "volatile",
  stable: "stable",
  immutable: "immutable",
} as const;

/** One value of the `volatility` vocabulary. */
export type Volatility = (typeof Volatility)[keyof typeof Volatility];

/** The `wire-class` vocabulary, in the catalog's own order. */
export const WireClass = {
  term: "term",
  frame: "frame",
  reply: "reply",
} as const;

/** One value of the `wire-class` vocabulary. */
export type WireClass = (typeof WireClass)[keyof typeof WireClass];

/** The `wire-payload` vocabulary, in the catalog's own order. */
export const WirePayload = {
  text: "text",
  number: "number",
  boolean: "boolean",
  term: "term",
  terms: "terms",
  host: "host",
  handle: "handle",
  truth: "truth",
  bindings: "bindings",
  control: "control",
} as const;

/** One value of the `wire-payload` vocabulary. */
export type WirePayload = (typeof WirePayload)[keyof typeof WirePayload];

/** The `world` vocabulary, in the catalog's own order. */
export const World = {
  closedWorld: "closed-world",
  openWorld: "open-world",
} as const;

/** One value of the `world` vocabulary. */
export type World = (typeof World)[keyof typeof World];

/**
 * Every vocabulary, by the engine's own name for it.
 *
 * The reflection door: a tool that must enumerate the closed sets reads this
 * rather than a list it keeps itself, and the sync test walks it against
 * `&metta`.
 */
export interface Vocabularies {
  readonly "ClauseFailedEnum": typeof ClauseFailedEnum;
  readonly "EvaluationOrderEnum": typeof EvaluationOrderEnum;
  readonly "FunctionResultEnum": typeof FunctionResultEnum;
  readonly "MismatchEnum": typeof MismatchEnum;
  readonly "NoMatchEnum": typeof NoMatchEnum;
  readonly "OutOfClausesEnum": typeof OutOfClausesEnum;
  readonly "agenda-policy": typeof AgendaPolicy;
  readonly "algebra-law": typeof AlgebraLaw;
  readonly "answer-policy": typeof AnswerPolicy;
  readonly "applicability": typeof Applicability;
  readonly "argument-delivery": typeof ArgumentDelivery;
  readonly "atomicity": typeof Atomicity;
  readonly "cache-policy": typeof CachePolicy;
  readonly "cost-class": typeof CostClass;
  readonly "delivery": typeof Delivery;
  readonly "delta-kind": typeof DeltaKind;
  readonly "determinism": typeof Determinism;
  readonly "effect-class": typeof EffectClass;
  readonly "event-order": typeof EventOrder;
  readonly "fidelity": typeof Fidelity;
  readonly "ground-kind": typeof GroundKind;
  readonly "image-mode": typeof ImageMode;
  readonly "journal-sync": typeof JournalSync;
  readonly "limit": typeof Limit;
  readonly "live-strategy": typeof LiveStrategy;
  readonly "memo-aggregate": typeof MemoAggregate;
  readonly "memo-strategy": typeof MemoStrategy;
  readonly "numeric-type": typeof NumericType;
  readonly "on-error-mode": typeof OnError;
  readonly "op-kind": typeof OpKind;
  readonly "provider-capability": typeof ProviderCapability;
  readonly "refinement": typeof Refinement;
  readonly "refusal-kind": typeof RefusalKind;
  readonly "registry-image": typeof RegistryImage;
  readonly "remedy-kind": typeof RemedyKind;
  readonly "route-key": typeof RouteKey;
  readonly "save-format": typeof SaveFormat;
  readonly "semiring": typeof Semiring;
  readonly "semiring-order": typeof SemiringOrder;
  readonly "source-kind": typeof SourceKind;
  readonly "space-capability": typeof SpaceCapability;
  readonly "subscription-edge": typeof SubscriptionEdge;
  readonly "visibility": typeof Visibility;
  readonly "volatility": typeof Volatility;
  readonly "wire-class": typeof WireClass;
  readonly "wire-payload": typeof WirePayload;
  readonly "world": typeof World;
}

/** Every vocabulary, by the engine's own name for it. */
export const VOCABULARIES: Vocabularies = {
  "ClauseFailedEnum": ClauseFailedEnum,
  "EvaluationOrderEnum": EvaluationOrderEnum,
  "FunctionResultEnum": FunctionResultEnum,
  "MismatchEnum": MismatchEnum,
  "NoMatchEnum": NoMatchEnum,
  "OutOfClausesEnum": OutOfClausesEnum,
  "agenda-policy": AgendaPolicy,
  "algebra-law": AlgebraLaw,
  "answer-policy": AnswerPolicy,
  "applicability": Applicability,
  "argument-delivery": ArgumentDelivery,
  "atomicity": Atomicity,
  "cache-policy": CachePolicy,
  "cost-class": CostClass,
  "delivery": Delivery,
  "delta-kind": DeltaKind,
  "determinism": Determinism,
  "effect-class": EffectClass,
  "event-order": EventOrder,
  "fidelity": Fidelity,
  "ground-kind": GroundKind,
  "image-mode": ImageMode,
  "journal-sync": JournalSync,
  "limit": Limit,
  "live-strategy": LiveStrategy,
  "memo-aggregate": MemoAggregate,
  "memo-strategy": MemoStrategy,
  "numeric-type": NumericType,
  "on-error-mode": OnError,
  "op-kind": OpKind,
  "provider-capability": ProviderCapability,
  "refinement": Refinement,
  "refusal-kind": RefusalKind,
  "registry-image": RegistryImage,
  "remedy-kind": RemedyKind,
  "route-key": RouteKey,
  "save-format": SaveFormat,
  "semiring": Semiring,
  "semiring-order": SemiringOrder,
  "source-kind": SourceKind,
  "space-capability": SpaceCapability,
  "subscription-edge": SubscriptionEdge,
  "visibility": Visibility,
  "volatility": Volatility,
  "wire-class": WireClass,
  "wire-payload": WirePayload,
  "world": World,
};

/** One vocabulary's engine name. */
export type VocabularyName = keyof Vocabularies;

/** Every value of one vocabulary, in the catalog's own order. */
export function valuesOf(vocabulary: VocabularyName): readonly string[] {
  return Object.values(VOCABULARIES[vocabulary]);
}

/** Whether a word is a value of one vocabulary. */
export function isValueOf(vocabulary: VocabularyName, word: string): boolean {
  return valuesOf(vocabulary).includes(word);
}

/**
 * How strong an effect class is, from structural purity to host I/O.
 *
 * The catalog declares the five in RANK ORDER, so the position in the row is
 * the rank and nothing here restates it.
 */
export function effectRank(effect: EffectClass): number {
  return valuesOf("effect-class").indexOf(effect);
}

/**
 * The strongest of several effect classes: the lattice join.
 *
 * A plan's effect is the strongest effect any step of it has, which is what
 * makes this a join rather than a sum. With no arguments the answer is the
 * bottom of the lattice, `pureStructural`, because a plan that does nothing
 * has no effect.
 */
export function joinEffects(...effects: readonly EffectClass[]): EffectClass {
  let strongest: EffectClass = EffectClass.pureStructural;
  for (const effect of effects) {
    if (effectRank(effect) > effectRank(strongest)) strongest = effect;
  }
  return strongest;
}
